# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

getDataGenotypeCpp <- function(chrCurr, geneTSSs, genotypeFile, tabixProgram, tempFileName, sampleIndices, cisDistance, MAFThreshold, MASamplesThreshold) {
    .Call(`_ClipperQTL_getDataGenotypeCpp`, chrCurr, geneTSSs, genotypeFile, tabixProgram, tempFileName, sampleIndices, cisDistance, MAFThreshold, MASamplesThreshold)
}

getTableMaxAbsCorsCpp <- function(Y, XRaw, dataCovariates, geneTSSs, SNPPositions, approach, B) {
    .Call(`_ClipperQTL_getTableMaxAbsCorsCpp`, Y, XRaw, dataCovariates, geneTSSs, SNPPositions, approach, B)
}

